name: Django Todo Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        compose-file: "docker-compose.yml"
        run: docker-compose up -d

    - uses: actions/checkout@v4
      with:
        compose-file: "docker-compose.yml"
        run: docker exec backend sh -c "flake8 && pytest ."
