name: Django Todo Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "docker-compose.yml"
        test-container: "container1"
        test-command: "pytest ."
